name: hd 
proxy:
  nginx:
    - hd.lndo.site
services:
  cli:  
    type: node:6
    build:
      - cd $LANDO_MOUNT/reveal.js && npm install
      - cd $LANDO_MOUNT/reveal.js && npm start 
  appserver:
    type: php:7.1
    via: nginx
    webroot: reveal.js
tooling:
  node:
    service: cli
  npm:
    service: cli

